name: Fetch READMEs and Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
  # 手动触发
  workflow_dispatch:
    inputs:
      publish_branch:
        description: "Branch to publish to"
        required: true
        default: "gh_pages"
      publish_dir:
        description: "Directory to publish"
        required: true
        default: "."

jobs:
  fetch-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: 检出当前仓库
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: 设置 Node.js 环境
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Step 3: 安装依赖
      - name: Install dependencies
        run: npm install axios marked

      # Step 4: 获取 README 文件
      - name: Fetch READMEs from repositories
        id: fetch-readmes
        run: |
          # 执行脚本
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} node fetch-readmes.js

      # # Step 5: 生成静态页面
      # - name: Generate static page
      #   run: |
      #     # 创建一个简单的 HTML 页面来展示 README 内容
      #     echo '
      #     <!DOCTYPE html>
      #     <html lang="en">
      #     <head>
      #       <meta charset="UTF-8">
      #       <meta name="viewport" content="width=device-width, initial-scale=1.0">
      #       <title>GitHub READMEs</title>
      #       <style>
      #         body { font-family: Arial, sans-serif; margin: 20px; }
      #         h1 { color: #333; }
      #         .repo { margin-bottom: 40px; }
      #         .repo h2 { color: #555; }
      #         .repo pre { background-color: #f4f4f4; padding: 10px; border-radius: 5px; }
      #       </style>
      #     </head>
      #     <body>
      #       <h1>GitHub READMEs</h1>
      #       <div id="content"></div>
      #       <script>
      #         const readmes = '$(cat readmes.json)';
      #         const data = JSON.parse(readmes);

      #         const container = document.getElementById("content");
      #         data.forEach(item => {
      #           const div = document.createElement("div");
      #           div.className = "repo";
      #           div.innerHTML = \`<h2>\${item.user}/\${item.repo}</h2><div>\${item.readme}</div>\`;
      #           container.appendChild(div);
      #         });
      #       </script>
      #     </body>
      #     </html>
      #     ' > index.html

      #Step 6: 部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
